# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "generate-resume-pdf"

[default.build]
[default.build.parameters]
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17lgq266ekvy9"
s3_prefix = "generate-resume-pdf"
region = "us-east-2"
image_repositories = ["HelloWorldFunction=810191593673.dkr.ecr.us-east-2.amazonaws.com/generateresumepdf8a167406/helloworldfunction19d43fc4repo"]

[default.sync]
[default.sync.parameters]
watch = true

[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda]
[default.local_start_lambda.parameters]
warm_containers = "EAGER"
